"""Export all FHIR resources from clinicaltrials360 HealthLake to sampledata/.

Writes one NDJSON file per resource type (one JSON object per line) plus a
manifest.json.  AI-generated insights DocumentReferences (type code
"ai-clinical-trial-insights") are written to a separate file so the import
script can skip them by default — they are regenerated by refresh_insights.py.

Usage:
    cd clinicaltrials
    set -a; source .env; set +a
    python3 infra/export_sampledata.py

Output:
    sampledata/
        manifest.json
        Patient.ndjson
        Condition.ndjson
        Observation.ndjson
        MedicationRequest.ndjson
        DocumentReference.ndjson          # non-AI clinical docs
        DocumentReference.insights.ndjson # AI insights (excluded from import by default)
        Questionnaire.ndjson
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import boto3
import requests
from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest

sys.path.insert(0, ".")
from config.settings import HEALTHLAKE_DATASTORE_ID

REGION = "us-east-1"
BASE = f"https://healthlake.{REGION}.amazonaws.com/datastore/{HEALTHLAKE_DATASTORE_ID}/r4"
OUT_DIR = Path("sampledata")

RESOURCE_TYPES = [
    "Patient",
    "Condition",
    "Observation",
    "MedicationRequest",
    "DocumentReference",
    "Questionnaire",
]

AI_DOC_TYPE_CODE = "ai-clinical-trial-insights"

_session = boto3.Session(region_name=REGION)
_creds = _session.get_credentials().get_frozen_credentials()


def _sign(method: str, url: str) -> dict:
    req = AWSRequest(method=method, url=url, headers={"Host": f"healthlake.{REGION}.amazonaws.com"})
    SigV4Auth(_creds, "healthlake", REGION).add_auth(req)
    return dict(req.headers)


def _fetch_all(resource_type: str) -> list[dict]:
    """Paginate through all resources of a given type."""
    resources: list[dict] = []
    url = f"{BASE}/{resource_type}?_count=100"

    while url:
        r = requests.get(url, headers=_sign("GET", url))
        r.raise_for_status()
        bundle = r.json()
        for entry in bundle.get("entry", []):
            res = entry.get("resource", {})
            if res.get("resourceType") == resource_type:
                resources.append(res)

        # HealthLake pagination tokens are pre-signed and cannot be re-signed.
        # Send subsequent pages unsigned (token is self-authenticating).
        next_link = next(
            (lnk["url"] for lnk in bundle.get("link", []) if lnk["relation"] == "next"),
            None,
        )
        if next_link and next_link != url:
            url = next_link
            # Use plain request for paginated URLs — re-signing breaks them
            def _get_plain(u: str) -> list[dict]:
                nonlocal url
                items: list[dict] = []
                while u:
                    resp = requests.get(u)
                    if not resp.ok:
                        resp = requests.get(u, headers=_sign("GET", u))
                    resp.raise_for_status()
                    b = resp.json()
                    for e in b.get("entry", []):
                        res2 = e.get("resource", {})
                        if res2.get("resourceType") == resource_type:
                            items.append(res2)
                    u = next(
                        (lnk["url"] for lnk in b.get("link", []) if lnk["relation"] == "next"),
                        None,
                    )
                return items
            resources.extend(_get_plain(next_link))
            break
        else:
            break

    return resources


def _is_ai_insights(doc: dict) -> bool:
    codings = doc.get("type", {}).get("coding", [])
    return any(c.get("code") == AI_DOC_TYPE_CODE for c in codings)


def main() -> None:
    if not HEALTHLAKE_DATASTORE_ID:
        print("ERROR: HEALTHLAKE_DATASTORE_ID is not set. Source your .env first.")
        sys.exit(1)

    OUT_DIR.mkdir(exist_ok=True)
    print(f"Exporting from datastore {HEALTHLAKE_DATASTORE_ID[:16]}… → {OUT_DIR}/")

    manifest: dict = {
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "datastore_id": HEALTHLAKE_DATASTORE_ID,
        "region": REGION,
        "files": {},
    }

    for rtype in RESOURCE_TYPES:
        print(f"  {rtype}…", end=" ", flush=True)
        resources = _fetch_all(rtype)

        if rtype == "DocumentReference":
            clinical_docs = [r for r in resources if not _is_ai_insights(r)]
            ai_docs = [r for r in resources if _is_ai_insights(r)]

            # Write clinical docs
            out_path = OUT_DIR / f"{rtype}.ndjson"
            with out_path.open("w") as f:
                for res in clinical_docs:
                    f.write(json.dumps(res, separators=(",", ":")) + "\n")
            manifest["files"][f"{rtype}.ndjson"] = len(clinical_docs)

            # Write AI insights separately
            ai_path = OUT_DIR / f"{rtype}.insights.ndjson"
            with ai_path.open("w") as f:
                for res in ai_docs:
                    f.write(json.dumps(res, separators=(",", ":")) + "\n")
            manifest["files"][f"{rtype}.insights.ndjson"] = len(ai_docs)

            print(f"{len(clinical_docs)} clinical + {len(ai_docs)} insights")
        else:
            out_path = OUT_DIR / f"{rtype}.ndjson"
            with out_path.open("w") as f:
                for res in resources:
                    f.write(json.dumps(res, separators=(",", ":")) + "\n")
            manifest["files"][f"{rtype}.ndjson"] = len(resources)
            print(len(resources))

    manifest_path = OUT_DIR / "manifest.json"
    with manifest_path.open("w") as f:
        json.dump(manifest, f, indent=2)

    total = sum(v for v in manifest["files"].values())
    print(f"\n✓ Exported {total} resources to {OUT_DIR}/")
    print(f"  Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
